[build-system]
requires = ["hatchling>=1.17.1", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "egamma-tnp"
description = "E/Gamma HLT efficiency from NanoAOD using Tag and Probe."
readme = "README.md"
license = {text = "BSD-3-Clause"}
requires-python = ">=3.8"
authors = [
  { name = "Iason Krommydas", email = "ik23@rice.edu" },
]
maintainers = [
    { name = "Iason Krommydas", email = "ik23@rice.edu" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Operating System :: MacOS",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Software Development",
  "Topic :: Utilities",
]
dependencies = [
  "coffea[dask] @ git+https://github.com/CoffeaTeam/coffea",
  "awkward>=2.3.3",
  "uproot>=5.0.10",
  "dask-awkward>=2023.6.3",
  "dask-histogram>=2023.6.0",
  "jupyterlab",
  "notebook",
  "nbclassic",
  "rucio-clients>=1.31",
  "distributed>=2023.4.0",
  "bokeh!=3.0.*,>=2.4.2",
  "mplhep>=0.3.28",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/iasonkrom/egamma-tnp"
"Bug Tracker" = "https://github.com/iasonkrom/egamma-tnp/issues"

[project.optional-dependencies]
dev = [
  "pre-commit",
  "black[jupyter]",
  "flake8",
  "pytest",
  "pytest-mpl",
]

[tool.hatch.version]
source = "vcs"
path = "src/egamma_tnp/__init__.py"

[tool.hatch.build.hooks.vcs]
version-file = "src/egamma_tnp/version.py"

[tool.setuptools_scm]
write_to = "src/egamma_tnp/_version.py"

[tool.hatch.metadata]
allow-direct-references = true
